// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package resources

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed tyr.png
var resourceTyrPngData []byte

// ResourceTyrPng is the embedded application icon
var ResourceTyrPng = &fyne.StaticResource{
	StaticName:    "tyr.png",
	StaticContent: resourceTyrPngData,
}

//go:embed tyr.ico
var resourceTyrIcoData []byte

// ResourceTyrIco is the embedded ICO icon for Windows system tray
var ResourceTyrIco = &fyne.StaticResource{
	StaticName:    "tyr.ico",
	StaticContent: resourceTyrIcoData,
}
