// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddPeer(arg1:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateBackup(arg1:main.BackupOptionsDTO):Promise<main.ResultDTO>;

export function DisablePeer(arg1:string):Promise<void>;

export function EnablePeer(arg1:string):Promise<void>;

export function GetConfig():Promise<main.ConfigDTO>;

export function GetDefaultPeers():Promise<Array<string>>;

export function GetMailAddress():Promise<string>;

export function GetPeerStats():Promise<Array<main.PeerInfoDTO>>;

export function GetServiceStatus():Promise<main.ServiceStatusDTO>;

export function GetSystemTheme():Promise<string>;

export function HideWindow():Promise<void>;

export function HotReloadPeers():Promise<void>;

export function InitializeService():Promise<void>;

export function IsOnboardingComplete():Promise<boolean>;

export function IsServiceRunning():Promise<boolean>;

export function MaximizeWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function OnStartupComplete():Promise<void>;

export function OpenDeltaChat():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function QuitApplication():Promise<void>;

export function RemovePeer(arg1:string):Promise<void>;

export function RestartService():Promise<void>;

export function RestoreBackup(arg1:main.RestoreOptionsDTO):Promise<main.ResultDTO>;

export function SaveConfig(arg1:main.ConfigDTO):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetOnboardingComplete():Promise<void>;

export function SetPassword(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function ShowErrorDialog(arg1:string,arg2:string):Promise<void>;

export function ShowMessageDialog(arg1:string,arg2:string):Promise<void>;

export function ShowOpenDirectoryDialog(arg1:string):Promise<string>;

export function ShowOpenFileDialog(arg1:string):Promise<string>;

export function ShowQuestionDialog(arg1:string,arg2:string):Promise<boolean>;

export function ShowSaveFileDialog(arg1:string,arg2:string):Promise<string>;

export function ShowWindow():Promise<void>;

export function StartService():Promise<void>;

export function StopService():Promise<void>;

export function ToggleMaximize():Promise<void>;

export function ToggleWindowVisibility():Promise<void>;
