// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPeer(arg1) {
  return window['go']['main']['App']['AddPeer'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateBackup(arg1) {
  return window['go']['main']['App']['CreateBackup'](arg1);
}

export function DisablePeer(arg1) {
  return window['go']['main']['App']['DisablePeer'](arg1);
}

export function EnablePeer(arg1) {
  return window['go']['main']['App']['EnablePeer'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDefaultPeers() {
  return window['go']['main']['App']['GetDefaultPeers']();
}

export function GetMailAddress() {
  return window['go']['main']['App']['GetMailAddress']();
}

export function GetPeerStats() {
  return window['go']['main']['App']['GetPeerStats']();
}

export function GetServiceStatus() {
  return window['go']['main']['App']['GetServiceStatus']();
}

export function GetSystemTheme() {
  return window['go']['main']['App']['GetSystemTheme']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function HotReloadPeers() {
  return window['go']['main']['App']['HotReloadPeers']();
}

export function InitializeService() {
  return window['go']['main']['App']['InitializeService']();
}

export function IsOnboardingComplete() {
  return window['go']['main']['App']['IsOnboardingComplete']();
}

export function IsServiceRunning() {
  return window['go']['main']['App']['IsServiceRunning']();
}

export function MaximizeWindow() {
  return window['go']['main']['App']['MaximizeWindow']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function OnStartupComplete() {
  return window['go']['main']['App']['OnStartupComplete']();
}

export function OpenDeltaChat() {
  return window['go']['main']['App']['OpenDeltaChat']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function QuitApplication() {
  return window['go']['main']['App']['QuitApplication']();
}

export function RemovePeer(arg1) {
  return window['go']['main']['App']['RemovePeer'](arg1);
}

export function RestartService() {
  return window['go']['main']['App']['RestartService']();
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetOnboardingComplete() {
  return window['go']['main']['App']['SetOnboardingComplete']();
}

export function SetPassword(arg1) {
  return window['go']['main']['App']['SetPassword'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function ShowErrorDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowErrorDialog'](arg1, arg2);
}

export function ShowMessageDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowMessageDialog'](arg1, arg2);
}

export function ShowOpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['ShowOpenDirectoryDialog'](arg1);
}

export function ShowOpenFileDialog(arg1) {
  return window['go']['main']['App']['ShowOpenFileDialog'](arg1);
}

export function ShowQuestionDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowQuestionDialog'](arg1, arg2);
}

export function ShowSaveFileDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowSaveFileDialog'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartService() {
  return window['go']['main']['App']['StartService']();
}

export function StopService() {
  return window['go']['main']['App']['StopService']();
}

export function ToggleMaximize() {
  return window['go']['main']['App']['ToggleMaximize']();
}

export function ToggleWindowVisibility() {
  return window['go']['main']['App']['ToggleWindowVisibility']();
}
